const AUTH = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  USERNAME: "USERNAME",
  ISVALID_USERNAME: "ISVALID_USERNAME",
  PASSWORD: "PASSWORD",
  ISVALID_PASSWORD: "ISVALID_PASSWORD",
};

const NOTE = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  FAVORITE: "FAVORITE",
  DELETE: "DELETE",
};

const CONTROL = {
  HIDE_NOTIFY: "HIDE_NOTIFY",
  SHOW_CREATE_DIALOG: "SHOW_DIALOG",
  SHOW_UPDATE_DIALOG: "SHOW_UPDATE_DIALIG",
  SHOW_DELETE_DIALOG: "SHOW_DELETE_DIALOG",
  CHANGE_NOTE_FAVORITE_STATUS: "CHANGE_NOTE_FAVORITE_STATUS",
  CLOSE_DIALOG: "CLOSE_DIALOG"
};

export { AUTH, NOTE, CONTROL };
